### ISSUE TITLE
As an AWS user, I want to analyze AWS CloudTrail logs so that I can reason about my account's security

### ISSUE THREAD

**Issue by sopel** [logsearch/logsearch-for-aws#2]
This story has been extracted from epic #1: The CloudTrail log data is utterly granular and meanwhile almost ubiquitously available across services and regions, thus the ultimate power data source to answer almost every question about AWS API usage. It can be facilitated for many scenarios accordingly, notably from the security realm.
- :information_source: see https://github.com/cityindex-attic/logsearch/issues/227 for the previous version of this story, which might contain some relevant additional information/thinking still.

**Comment by sopel** [comment]
## Scenarios

There is an open ended number of interesting scenarios conceivable, so this is just to list some  obvious ones to get started:

### Security
- auditing - after the fact analysis who did what when
- debugging - after the fact analysis which lack of permissions causes something to fail
- monitoring - during the fact detection of unexpected API usage
  - in its simplest form, this can simply detect a permission change gone wrong or credentials improperly rotated etc.
  - in its more advanced form this use case requires anomaly detection and machine learning down the road, though high security scenarios certainly require more thorough and immediate intrusion detection measures
- requirements analysis - a strong best practice in security in general and AWS/IAM in particular is to converge to a 'least privilege' approach. While IAM offers almost anything required in this regard, deducing a software's necessary IAM permissions requires either thorough bookkeeping or code analysis during development - CloudTrail can also answer this by simply recording all API actions performed while exercising the software (for example from functional and integration tests - obviously high code coverage is a pre condition here)

**Comment by sopel** [comment]
### Implementation Notes

@mrdavidlaing - @dpb587 and I discussed how to get started with this, here are a couple of brief notes:
- there's a strong preference to base this on [CloudTrail push notifications](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/getting_notifications_top_level.html) on log file delivery (by means of the usual indirection via an Amazon SQS queue), rather than say polling the S3 bucket directly, which requires state management and is wasteful on resources
  - [ ] the SQS queue will be maintained via a CloudFormation template in the Logsearch context
- while AWS offers a [CloudTrail Processing Libary (CPL)]() for Java for advanced integration scenarios, the use case at hand strongly suggests to facilitate the [Logstash SQS](http://logstash.net/docs/latest/inputs/sqs) and/or [Logstash S3](http://logstash.net/docs/latest/inputs/s3) inputs instead
- there's some overlap with the S3 archiving job, thus resp. bits and pieces might be reusable
- the script getting the log file from S3 requires read access to this highly restricted bucket - so far usage of the AWS CLI has been avoided to skip the required Python dependency chain, thus alternate options might be:
  - signing the S3 GET requests as needed by means of OpenSSL (seems brittle)
  - adding an S3 bucket policy constrained by some applicable IAM condition, like the gateway IP address for example (seems easy)
  - we settled on the latter as a pragmatic and easy to implement first step, which should be revisited from a least privilege security PoV once this is working as desired
  - [ ] the S3 bucket policy will be maintained via a CloudFormation template in the Logsearch context

**Comment by mrdavidlaing** [comment]
@sopel; if I understand correctly, we'll basically be treating the creation of the SQS queue, S3 bucket and IAM permissions on both as part of the "environment" which Logsearch must be deployed into.

If so, :+1: from me

**Comment by sopel** [comment]
:information_source: this story is on hold until #5 is going to be resolved.

**Comment by dpb587** [comment]
Closing this - we have support for ingesting CloudTrail logs. Handled by lower level S3 notifications though, not CloudTrail notifications as initially stated here (it's possible... just lazy right now since the job would only used by a single log type).
