### ISSUE TITLE
Provide explicit type mappings for ingested logs

### ISSUE THREAD

**Issue by sopel** [logsearch/logsearch-for-aws#5]
While the implicit type mappings are sufficient for exploration, most more pronounced use cases imply drill down needs which almost always require wildcard based exclusions etc.
- This primarily blocks progress on #2, but also impacts #4 for similar reasons.

Accordingly, these need to be enabled via explicit mappings. 
- :information_source: Worth noting that the need for explicit mappings has come up in pretty much all `logsearch-for-*` sub projects and suggests a respectively generic approach for managing those accordingly.

**Comment by dpb587** [comment]
I've committed type mappings for the three current log types to [`./src/logsearch-config/logs`](https://github.com/logsearch/logsearch-for-aws/tree/master/src/logsearch-config/logs).
